/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BtnIptList: typeof import('./src/components/BtnIptList.vue')['default']
    BtnTable: typeof import('./src/components/BtnTable.vue')['default']
    Model: typeof import('./src/components/Model.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/Swiper.vue')['default']
  }
}
